FROM maven:3.9.8-eclipse-temurin-21 AS builder
WORKDIR /build
COPY pom.xml ./
RUN mvn dependency:go-offline -B
COPY . .
RUN mvn package -DskipTests

FROM gcr.io/distroless/java21-debian12
COPY --from=builder /build/target/metricservice-0.0.1-SNAPSHOT.jar metrics-service.jar
ENTRYPOINT ["java", "-jar", "metrics-service.jar"]